#!/bin/bash
#
# THIS MUST RUN ON THE EUCALYPTUS SERVER
#
#
#
# $1 = account $2 = email $3 = password $4 = hashstring
#

CREDENITAL_BASE_LOCATION='/usr/share/eucalyptus-console/static/help/creds/'

if [ $# -ne 4 ]
  then
    echo "Error: Unexpected number of parmeters"
    exit 1
fi


euare-accountcreate -a $1 || { echo "Error creating account: $?"; exit; }
euare-usermodloginprofile --as-account $1 -u admin -p $3 || { echo "Error setting password: $?"; exit; }
euare-userupdateinfo --as-account=$1 -u admin -k email -i $2 || { echo "Error setting email: $?"; exit; }
euare-usermod -u admin --as-account $1 --pwd-expires '2023-03-02T00:00:00Z'


# Now confirm output
euare-usergetinfo -u admin --as-account $1
euare-usergetattributes -u admin --as-account $1 --show-extra

#
# Download the user's credentials (.zip) file and store it
# somewhere they can download it from easily.
#
euca-get-credentials -a $1 $CREDENITAL_BASE_LOCATION/$4$1.zip || { echo "Error creating or posting credentials: $?"; exit; }
